### ISSUE TITLE
Feature Request: support merged manifests

### ISSUE THREAD

**Issue by garylavayou** [jantari/rewinged#17]
### Problem Description

When using `winget download` to download those packages, the downloaded package contains a manifest file with `ManifestType` set to `merged`, which cannot be recognized by rewinged with the following error message.

```json
{
    "level":"error",
    "package":"Microsoft.VisualStudioCode",
    "packageversion":"1.100.2",
    "time":"2025-05-26T05:08:04Z",
    "message":"merged manifests are not yet supported"
}
```

Merged manifests may come from packages with [multiple manifest files](https://learn.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cinstaller-example#multiple-manifest-files), take [VS Code](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/VisualStudioCode/1.100.0) as a example, which includes manifests of type `version`, `defaultLocale`, and `installer`.

I try to manually update the `ManifestType` from `merged` to `singleton`, which works for some packages, e.g., `Microsoft.Edge`, and `voidtools.Everything`. But for some packages, e.g., `Google.Chrome`, this does not work with error message:

```json
{
    "level":"error",
    "error":"unsupported SingletonManifest version 1.10.0",
    "package":"Google.Chrome",
    "packageversion":"137.0.7151.41",
    "time":"2025-05-26T05:24:35Z",
    "message":"could not parse singleton manifest"
}
```

> **Note**: This problem is related to [not yet supporting schema version 1.10.0](https://github.com/jantari/rewinged/issues/14). After replacing 1.10.0 with 1.9.0, the problem is solved.
> Thus, the cause of this problem is not about "rewinged could not parse the **singleton** manifest".

### Suggested Change

- The "merged" type of manifest can be treated as a singleton manifest adding some metadata and locale data, so support for this type of manifest might be intuitive.
- Even if there might be some extra work to support the "merged" type, a fallback mechanism may be early adopted to treat this type as a singleton manifest by ignoring unknown fields.

**Comment by jantari** [comment]
The `merged` manifests are unfortunately not documented, but from what I can tell they're exactly like singleton manifests except that they allow more than 1 installer. This means it should be possible to support them as well.

I never want to ignore fields or parse incorrect data, if there is a problem rewinged is designed to fail early and lets the user fix the problematic manifest(s).

**Comment by joeblew999** [comment]
Hey

If there are examples in the repo, I can work on this.

**Comment by garylavayou** [comment]
> Hey
> 
> If there are examples in the repo, I can work on this.

@joeblew999 Here is one of the manifest files that are detected as "merged manifests" (even, I have modified the **ManifestType** from `merged` to `singleton`, and **ManifestVersion** from `1.10.0` to `1.9.0` based on my previous experience).

> ManifestVersion `1.10.0` has been supported since [v0.13.0-rc.1](https://github.com/jantari/rewinged/releases/tag/v0.13.0-rc.1),
> the rewinged version I use is `0.14.0`.

```yaml
PackageIdentifier: Hashicorp.Vagrant
PackageVersion: 2.4.9
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://developer.hashicorp.com/vagrant/docs
- DocumentLabel: Tutorials
  DocumentUrl: https://developer.hashicorp.com/vagrant/tutorials
Tags:
- develop
- development
- virtualization
PackageLocale: en-US
Author: HashiCorp, Inc.
Copyright: Copyright (c) 2024 HashiCorp, Inc.
Description: Vagrant is a tool for building and managing virtual machine environments
  in a single workflow. With an easy-to-use workflow and focus on automation, Vagrant
  lowers development environment setup time, increases production parity, and makes
  the "works on my machine" excuse a relic of the past.
ShortDescription: Build and manage virtual machine environments in a single workflow
License: BUSL-1.1
LicenseUrl: https://github.com/hashicorp/vagrant/blob/HEAD/LICENSE
PackageName: Vagrant
PackageUrl: https://developer.hashicorp.com/vagrant
PrivacyUrl: https://www.hashicorp.com/privacy
Publisher: HashiCorp
PublisherSupportUrl: https://github.com/hashicorp/vagrant/issues
PublisherUrl: https://www.hashicorp.com/
ReleaseNotes: https://github.com/hashicorp/vagrant/blob/HEAD/CHANGELOG.md#249-august-21-2025
ReleaseNotesUrl: https://github.com/hashicorp/vagrant/blob/HEAD/CHANGELOG.md#245-april-23-2025
Localization:
- Documentations:
  - DocumentLabel: "\u6587\u6863"
    DocumentUrl: https://developer.hashicorp.com/vagrant/docs
  - DocumentLabel: "\u6559\u7A0B"
    DocumentUrl: https://developer.hashicorp.com/vagrant/tutorials
  Tags:
  - "\u5F00\u53D1"
  - "\u865A\u62DF\u5316"
  PackageLocale: zh-CN
  Description: "Vagrant \u662F\u4E00\u6B3E\u7528\u4E8E\u5728\u5355\u4E00\u5DE5\u4F5C\u6D41\u4E2D\u6784\u5EFA\u548C\u7BA1\u7406\u865A\u62DF\u673A\u73AF\u5883\u7684\u5DE5\u5177\u3002\u51ED\u501F\u5176\u7B80\u5355\u6613\u7528\u7684\u5DE5\u4F5C\u6D41\u7A0B\u548C\u5BF9\u81EA\u52A8\u5316\u7684\u4E13\u6CE8,Vagrant
    \u663E\u8457\u7F29\u77ED\u4E86\u5F00\u53D1\u73AF\u5883\u642D\u5EFA\u65F6\u95F4,\u63D0\u9AD8\u4E86\u751F\u4EA7\u73AF\u5883\u4E00\u81F4\u6027,\u8BA9\u201C\u5728\u6211\u673A\u5668\u4E0A\u80FD\u8DD1\u201D\u7684\u6258\u8F9E\u6210\u4E3A\u5386\u53F2\u3002"
  ShortDescription: "\u5728\u5355\u4E00\u5DE5\u4F5C\u6D41\u4E2D\u6784\u5EFA\u548C\u7BA1\u7406\u865A\u62DF\u673A\u73AF\u5883"
  ReleaseNotes: https://github.com/hashicorp/vagrant/blob/HEAD/CHANGELOG.md#249-august-21-2025
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerSha256: 3bdd967927705872a70c7c98e0576afd5acd9dd73b527695f4d9dd75dd26cbe3
  # InstallerUrl: https://releases.hashicorp.com/vagrant/2.4.9/vagrant_2.4.9_windows_amd64.msi
  InstallerUrl: https://files.garylavayou.imwork.net:8443/softwares/hashicorp/vagrant/Hashicorp.Vagrant_2.4.9/Vagrant_2.4.9_Machine_X64_wix_zh-CN.msi
  Scope: machine
  ReleaseDate: 2025-08-21
  InstallerAbortsTerminal: false
  InstallLocationRequired: false
  RequireExplicitUpgrade: false
  DisplayInstallWarnings: false
  DownloadCommandProhibited: false
  ProductCode: '{865E13BB-1BDF-4867-9093-18817E1A4CBF}'
  UpgradeBehavior: install
  RepairBehavior: unknown
  Commands:
  - vagrant
  AppsAndFeaturesEntries:
  - UpgradeCode: '{1A672674-6722-4E3A-9061-8F539A8B0ED6}'
  ExpectedReturnCodes:
  - InstallerReturnCode: 87
    ReturnResponse: invalidParameter
  - InstallerReturnCode: 112
    ReturnResponse: diskFull
  - InstallerReturnCode: 1601
    ReturnResponse: contactSupport
  - InstallerReturnCode: 1602
    ReturnResponse: cancelledByUser
  - InstallerReturnCode: 1618
    ReturnResponse: installInProgress
  - InstallerReturnCode: 1623
    ReturnResponse: systemNotSupported
  - InstallerReturnCode: 1625
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1628
    ReturnResponse: invalidParameter
  - InstallerReturnCode: 1633
    ReturnResponse: systemNotSupported
  - InstallerReturnCode: 1638
    ReturnResponse: alreadyInstalled
  - InstallerReturnCode: 1639
    ReturnResponse: invalidParameter
  - InstallerReturnCode: 1640
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1641
    ReturnResponse: rebootInitiated
  - InstallerReturnCode: 1643
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1644
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1649
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1650
    ReturnResponse: invalidParameter
  - InstallerReturnCode: 1654
    ReturnResponse: systemNotSupported
  InstallerSwitches:
    Silent: /quiet /norestart
    SilentWithProgress: /passive /norestart
    Log: /log "<LOGPATH>"
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  InstallerSuccessCodes:
  - 1706
  - 3010
ManifestVersion: 1.9.0
ManifestType: singleton
```
